defaults: &defaults
  http_basic_name: preview
  http_basic_password: future # Update this in production
  test_user_password: password

  # Deployment recipe settings
  application_name: "BillUp"
  gemset_name: "billup-rails.3.1.x"
  ruby_version: "ruby-1.9.3-p0"
  server_name: "billup.net"
  user: "silumesii"

  # Email settings
  email_address: "smtp.gmail.com"
  email_domain: "gmail.com"
  email_password: "password" # Update this in production
  email_port: 587
  email_user_name: "hello@billup.net"


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
